#Template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-MSBuild.yml
name: Build

env:
  Branch: ${{github.ref_name}}
  Platform: #Any CPU|Win32|x64
  Configuration: Release
  Artifacts: build/$Configuration
  Solution: ${{github.event.repository.name}}.sln # .
  Executable: ${{github.event.repository.name}}.exe # *
  
on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Windows:
    runs-on: windows-2019
    steps:

    - name: Clone repo and submodules
      run: git clone --recurse-submodules https://github.com/${{github.repository}}.git . --branch ${{env.Branch}}

    - name: Get current date, commit hash and count
      run: |
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        msbuild /m ${{env.Solution}} #/p:Configuration="${{env.Configuration}}" /p:Platform="${{env.Platform}}"
#        msbuild /m ${{env.Solution}} #/p:Configuration="${{env.Configuration}}" /p:Platform="${{env.Platform}}" /p:IncludePath="C:\Path\to\Include" /p:LibPath="C:\Path\to\Lib" /p:AdditionalIncludePaths="C:\Path\to\external\include" /p:AdditionalLibraryDirectories="C:\Path\to\external\lib" /p:LanguageStandard="stdcpp17"

    - name: Deploy
      run: |
        windeployqt.exe "${{github.workspace}}/${{env.Artifacts}}/${{env.Solution}}"

    - name: List files
      run: ls -R

    - name: Upload Installer Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: "${{github.event.repository.name}}_r${{env.CommitCount}}@${{env.CommitHashShort}}"
        path: "${{github.workspace}}/${{env.Artifacts}}/"

    - name: Compress artifacts
      uses: vimtor/action-zip@v1.1
      with:
        files: '${{env.Artifacts}}/'
        dest: "build/${{github.event.repository.name}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: GitHub pre-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "[${{env.CommitDate}}] ${{github.event.repository.name}} r${{env.CommitCount}}@${{env.CommitHashShort}}"
        files: "build/${{github.event.repository.name}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
